### ISSUE TITLE
Problems installing on Rakudo 2017.07

### ISSUE THREAD

**Issue by nige123** [bduggan/p6-digest-sha1-native#7]
Received the following error when upgrading to Rakudo 2017.07:

===SORRY!=== Error while compiling /home/s3/z.co/home#sources/8922A2BA7BE89CE9C1AF2017551EC8B1435BA924 (Digest::SHA1::Native)
An exception occurred while evaluating a constant
at /home/s3/z.co/home#sources/8922A2BA7BE89CE9C1AF2017551EC8B1435BA924 (Digest::SHA1::Native):5
Exception details:
  No such method 'abspath' for invocant of type 'Distribution::Resource'
    in block  at /home/nige/.perl6/sources/8922A2BA7BE89CE9C1AF2017551EC8B1435BA924 (Digest::SHA1::Native) line 5

Does abspath need to be changed to IO.absolute?

**Comment by bduggan** [comment]
Hi!

This was [changed](https://github.com/bduggan/p6-digest-sha1-native/blob/master/lib/Digest/SHA1/Native.pm6#L5) to` absolute` a while ago (9e46cec) -- looks like maybe you're trying to install an earlier version.

Brian
